Knigochei/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace Knigochei.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get { return $"{FirstName} {LastName}"; } } 
        public string AvatarImagePath { get; set; }
        public DateTime BirthDate { get; set; }
        public int GenderId { get; set; }
        public bool IsDeleted { get; set; }
    }
}

Knigochei/Controllers/AuthorController.cs
using Knigochei.Forms;
using Knigochei.Models;
using Knigochei.Services.AuthorService;
using Knigochei.Services.GenreService;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;

namespace Knigochei.Controllers
{
    public class AuthorController : Controller
    {

        private IAuthorService _authorService;
        private IGenreService _genreService;
        public AuthorController(IAuthorService authorService, IGenreService genreService)
        {
            _authorService = authorService;
            _genreService = genreService;
        }

        public IActionResult Index(AuthorFilterFormModel formModel)
        {
            List<Author> authors = _authorService.GetFilteredAuthorsByGenre(formModel.GenreId);
            _authorService.FilterAuthorsByFirstName(ref authors, formModel.FirstName);
            _authorService.FilterAuthorsByLastName(ref authors, formModel.LastName);
            _authorService.SortAuthorsByFirstNameDesc(ref authors, formModel.OrderByFirstNameDesc);

            List<Genre> allGenres = _genreService.GetAllGenres();

            ViewData["genres"] = allGenres;
            ViewData["authors"] = authors;

            return View();
        }

        



    }
}

Knigochei/Views/Author/Index.cshtml
@model Knigochei.Forms.AuthorFilterFormModel

@{
    ViewData["Title"] = "Авторы";
}


<div class="container-fluid" style="background-color: white;">
	<div class="row text-center">
		<div class="col-md-2 pt-3 pb-3" id="params">
			@using(Html.BeginForm("Index", "Author", FormMethod.Get))
			{
			<div class="row"> 
				<label class="mt-2 mr-2"> Искать по фамилии:</label> <br>
				<input type="text" asp-for="LastName" class="mt-2" placeholder="Фамилия">
			</div> <br>
			<div class="row"> 
				<label class="mt-2 mr-2"> Искать по имени:</label> <br>
				<input type="text" asp-for="FirstName" class="mt-2" placeholder="Имя"> 
			</div><br>
			<div class="row"> 
				<label class="col-md-4 mt-2 "> Жанр: </label>
				<select asp-for="GenreId" class="inp mt-2">
					<option value=0>Все</option>
					@foreach(var genre in ViewData["genres"] as List<Genre>)
					{
						<option value=@genre.Id>@genre.GenreName</option>
					}
				</select>
			</div> 
			<br>
				<div class="row"> 
					<label class="col-md-9 mt-2 ms-1">По&nbsp;убыванию:</label> 
					<input type="checkbox" asp-for="OrderByFirstNameDesc" id="check" class="col-md-2 mt-2"> 
				</div> <br>
					<input type="submit" name="settings" value="Применить">
			}
		</div>

		<div class="col-md-8 mt-4 ps-5 ms-5">
			<h2> Представляем Вашему вниманию авторов, чьи книги есть в нашей коллекции:</h2>
			<div class="row ms-5 mt-5"> 
				
				@foreach(var author in ViewData["authors"] as List<Author>) 
				{
					<div class="card mb-3 pt-3 me-2" style="width: 18rem;">
						<img src=@Url.Content(author.AvatarImagePath) style="width: 50%" class="card-img-top" alt="...">
						<div class="card-body">
							<h4>@author.FullName</h4> 
							<hr>
							<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
						</div>
					</div>
				}
				
			</div>	
		</div>
	</div>
</div>
<br> <br> <br> <br> <br> <br> <br> <br>