Knigochei/ViewModels/BookPageViewModel.cs
using Knigochei.Models;

namespace Knigochei.ViewModels
{
    public class BookPageViewModel
    {
        public Book Book { get; set; }
        public Author Author { get; set; }
        
    }
}

Knigochei/Controllers/CartController.cs
using Knigochei.Models;
using Knigochei.Services.AuthorService;
using Knigochei.Services.BookService;
using Knigochei.Services.CartService;
using Knigochei.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Knigochei.Controllers
{
    [Authorize(Roles="Admin,Customer")]
    public class CartController : Controller
    {

        private ICartService _cartService;
        private IBookService _bookService;
        private IAuthorService _authorService;

        public CartController(ICartService cartService, IBookService bookService, IAuthorService authorService)
        {
            _cartService = cartService;
            _bookService = bookService;
            _authorService = authorService;
        }

        public IActionResult Index()
        {
            int userId = GetUserId();
            _cartService.CreateUserCartIfNotExists(userId);

            List<CartItem> cartItems = _cartService.GetAllCartItemsByCart(userId);
            List<CartItemViewModel> cartItemViewModels = ConvertCartItemViewsToViewModel(cartItems).ToList();

            return View(cartItemViewModels);
        }

        [HttpPost]
        public IActionResult AddToCart(int bookId)
        {
            int userId = GetUserId();
            _cartService.CreateUserCartIfNotExists(userId);

            if(_cartService.ExistsCartItem(userId, bookId))
            {
                _cartService.UpdateUserCartItemAmountOrIncrement(userId, bookId);
            } else
            {
                _cartService.AddBookToCart(userId, bookId);
            }

            return new JsonResult("success");
        }
        [HttpPost]
        public IActionResult UpdateCartItemAmount(CartItem cartItem)
        {
            int userId = GetUserId();
            _cartService.UpdateUserCartItemAmountOrIncrement(userId, cartItem.BookId, cartItem.Amount);

            return new JsonResult("Success");
        }

        [HttpDelete]
        public IActionResult DeleteFromCart(int bookId)
        {
            int userId = GetUserId();
            _cartService.DeleteFromUserCartByBook(userId, bookId);

            return new JsonResult("Deleted Successfully");
        }


        public int GetUserId()
        {
            string userIdClaimValue = HttpContext.User.Claims
                .Where(claim => claim.Type == ClaimTypes.NameIdentifier)
                .Select(claim => claim.Value)
                .FirstOrDefault();


            return Convert.ToInt32(userIdClaimValue);
        }

        public IEnumerable<CartItemViewModel> ConvertCartItemViewsToViewModel(IEnumerable<CartItem> cartItems)
        {
            return cartItems.Select(cartItem =>
            {
                CartItemViewModel cartItemView = new CartItemViewModel();
                cartItemView.Book = _bookService.GetBookById(cartItem.BookId);
                cartItemView.Author = _authorService.GetAuthorById(cartItemView.Book.AuthorId);
                cartItemView.CartItem = cartItem;

                return cartItemView;
            });
        }
    }
}

Knigochei/Controllers/CatalogController.cs
using Knigochei.Forms;
using Knigochei.Models;
using Knigochei.Repository.BookRepo;
using Knigochei.Services.AuthorService;
using Knigochei.Services.BookService;
using Knigochei.Services.GenreService;
using Knigochei.UnitOfWorkDapper;
using Knigochei.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Knigochei.Controllers
{
    public class CatalogController : Controller
    {
        private IBookService _bookService;
        private IAuthorService _authorService;
        private IGenreService _genreService;

        public CatalogController(IBookService bookService, IGenreService genreService, IAuthorService authorService)
        {
            _bookService = bookService;
            _genreService = genreService;
            _authorService = authorService;
        }
        public IActionResult Index(CatalogFilterFormModel model)
        {
            List<Book> books = _bookService.GetAllBooks();
            List<Genre> allGenres = _genreService.GetAllGenres();

            _bookService.FilterBooksByPrice(ref books, model.PriceMin, model.PriceMax);
            _bookService.FilterBooksByGenre(ref books, model.GenreId);

            _bookService.SortBooksByDesc(ref books, model.OrderByPriceDesc);

            ViewData["books"] = books;
            ViewData["genres"] = allGenres;


            return View();
        }

        [HttpGet]
        [Route("Catalog/Book/{bookId:int}")]
        public IActionResult BookPage(int bookId)
        {
            Book book = _bookService.GetBookById(bookId);
            if (book.Id == 0) return View("Error");

            Author author = _authorService.FindAuthorByBook(book.Id);

            var model = new BookPageViewModel();
            model.Book = book;
            model.Author = author;

            return View(model);
        }


        
    }
}

Knigochei/Views/Catalog/BookPage.cshtml
@model Knigochei.ViewModels.BookPageViewModel


@{
    ViewData["Title"] = Model.Book.Title;
}


<div class="container-fluid">
	<div class="row mt-5">
		<div class="col-md-3"></div>

		<div id="item-body" class="col-md-6 p-5">
			<div class="row text-center">
				<div class="col-md-5 w-50" id="cover">
					<img src=@Url.Content(Model.Book.CoverImagePath)>
				</div>
				<div class="col-md-6 " id="description">
					<h3 class="text-center pt-6">@Model.Book.Title</h3>
					<h5 class="text-center"> @Model.Author.FullName </h5>
					<hr>
					<div class="text-center pb-3">
						@for(int i = 0; i < Model.Book.BookRank; i++)
						{
							<i class="bi bi-star-fill"></i>
						}
					</div>
					<p>
						@Model.Book.BookDescription
					</p>
					<button class="p-2 ps-3 pe-3" onclick="AddToCart(@Model.Book.Id)"> <i class="bi bi-plus-circle"></i> Добавить в корзину </button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6 pt-5"> 
				<h3 class="text-center"> Комментарии:</h3>
				<br>
				<div class="comment row pt-3 pb-2">
					<i class="bi bi-person-circle col-md-2 text-center"></i>
					<div class="col-md-9 pt-2">
						<span> Hey do you think I should read this book? </span> <br>
						<span style="color: grey"> 05.05.2022 </span> 
					</div>
				</div>

				<div class="comment row pt-3 pb-2">
					<i class="bi bi-person-circle col-md-2 text-center"></i>
					<div class="col-md-9 pt-2">
						<span> Of course, definitely. </span> <br>
						<span style="color: grey"> 05.05.2022 </span> 
					</div>
				</div>
				<div class="comment row pt-3 pb-2">
					<i class="bi bi-person-circle col-md-2 text-center"></i>
					<div class="col-md-9 pt-2">
						<span> Hey, this is the best book I've read, of course you should read it! </span> <br>
						<span style="color: grey"> 05.05.2022 </span> 
					</div>
				</div>

				<div class="comment row pt-3 pb-2">
					<i class="bi bi-person-circle col-md-2 text-center"></i>
					<div class="col-md-9 pt-2">
						<span> Hey do you think I should read this book? </span> <br>
						<span style="color: grey"> 05.05.2022 </span> 
					</div>
				</div>
			</div>
			<div class="col-md-3"></div>
		</div>

	</div>
</div>
<br> <br> <br> <br>

<script>

	function AddToCart(bookId) {
			$.ajax({
				url:"/Cart/AddToCart",
				method: "POST",
				data: { "bookId": bookId },
				success: function(data, status) {
					alert("Successfully Added To Cart!")
					let cartUrl = '@Url.Action("Index", "Cart")';
					location.href=cartUrl;
				},
				error: function(error) {
					alert("Failed To Add to Cart! Error: ")
					console.log(error)

				}
				
			})
		}

</script>

Knigochei/Views/Catalog/Index.cshtml
@model Knigochei.Forms.CatalogFilterFormModel


@{
    ViewData["Title"] = "Каталог";
}


<div class="container-fluid">
		<div class="row text-center">
			<div class="col-md-2 pt-3 pb-3" id="params">
				@using(Html.BeginForm("Index", "Catalog", FormMethod.Get))
				{
					<div class="row"> 
						<label class="col-md-4 mt-2 mr-2"> От:</label>
						<input type="text" asp-for="PriceMin" class="inp mt-2 col-md-9" pattern="[0-9]+" placeholder="1000">
					</div> <br>
					<div class="row"> 
						<label class="col-md-4 mt-2 mr-2"> До:</label>
						<input type="text" asp-for="PriceMax" class="inp mt-2" pattern="[0-9]+" placeholder="10000"> 
					</div><br>
					<div class="row"> 
						<label class="col-md-4 mt-2 "> Жанр: </label>
						<select asp-for="GenreId" class="inp mt-2">
							<option value=0>Все</option>
							@foreach(var genre in ViewData["genres"] as List<Genre>)
							{
								<option value=@genre.Id>@genre.GenreName</option>
							}
						</select> 
					</div> <br>
						<div class="row"> 
							<label class="col-md-9 mt-2 ms-1">По&nbsp;убыванию:</label> 
							<input type="checkbox" asp-for="OrderByPriceDesc" class="col-md-2 mt-2"> 
						</div> <br>
							<input type="submit" name="settings" value="Применить">
				}
			</div>
					<div class="col-md-8 mt-4 ps-5 ms-5">
						<div class="row ms-5">
						@foreach(var book in ViewData["books"] as List<Book>)
						{
								 
							<div class="card mb-3 pt-3 me-2" style="width: 18rem;" onclick="openBookPage(@book.Id)">

							<img src=@Url.Content(book.CoverImagePath) style="width: 50%" class="card-img-top" alt="@book.Title">
								
								<div class="card-body">
									<p class="card-text">@book.Title</p>
									<p class="card-text">Price: @book.Price</p>
									<p class="card-text">@book.BookDescription</p>
								</div>
							</div>
						}
						</div>

							
					</div>
		</div>
</div>

<br /><br /><br /><br /><br />
<script> 
	function openBookPage(bookId) {
		let bookPageUrl = '@Url.Action("Book", "Catalog")/'+bookId;
		console.log(bookPageUrl);

		location.href=bookPageUrl;
	}

</script>