Knigochei/Models/Cart.cs
namespace Knigochei.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public int UserId { get; set; }
    }
}

Knigochei/Controllers/CartController.cs
using Knigochei.Models;
using Knigochei.Services.AuthorService;
using Knigochei.Services.BookService;
using Knigochei.Services.CartService;
using Knigochei.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Knigochei.Controllers
{
    [Authorize(Roles="Admin,Customer")]
    public class CartController : Controller
    {

        private ICartService _cartService;
        private IBookService _bookService;
        private IAuthorService _authorService;

        public CartController(ICartService cartService, IBookService bookService, IAuthorService authorService)
        {
            _cartService = cartService;
            _bookService = bookService;
            _authorService = authorService;
        }

        public IActionResult Index()
        {
            int userId = GetUserId();
            _cartService.CreateUserCartIfNotExists(userId);

            List<CartItem> cartItems = _cartService.GetAllCartItemsByCart(userId);
            List<CartItemViewModel> cartItemViewModels = ConvertCartItemViewsToViewModel(cartItems).ToList();

            return View(cartItemViewModels);
        }

        [HttpPost]
        public IActionResult AddToCart(int bookId)
        {
            int userId = GetUserId();
            _cartService.CreateUserCartIfNotExists(userId);

            if(_cartService.ExistsCartItem(userId, bookId))
            {
                _cartService.UpdateUserCartItemAmountOrIncrement(userId, bookId);
            } else
            {
                _cartService.AddBookToCart(userId, bookId);
            }

            return new JsonResult("success");
        }
        [HttpPost]
        public IActionResult UpdateCartItemAmount(CartItem cartItem)
        {
            int userId = GetUserId();
            _cartService.UpdateUserCartItemAmountOrIncrement(userId, cartItem.BookId, cartItem.Amount);

            return new JsonResult("Success");
        }

        [HttpDelete]
        public IActionResult DeleteFromCart(int bookId)
        {
            int userId = GetUserId();
            _cartService.DeleteFromUserCartByBook(userId, bookId);

            return new JsonResult("Deleted Successfully");
        }


        public int GetUserId()
        {
            string userIdClaimValue = HttpContext.User.Claims
                .Where(claim => claim.Type == ClaimTypes.NameIdentifier)
                .Select(claim => claim.Value)
                .FirstOrDefault();


            return Convert.ToInt32(userIdClaimValue);
        }

        public IEnumerable<CartItemViewModel> ConvertCartItemViewsToViewModel(IEnumerable<CartItem> cartItems)
        {
            return cartItems.Select(cartItem =>
            {
                CartItemViewModel cartItemView = new CartItemViewModel();
                cartItemView.Book = _bookService.GetBookById(cartItem.BookId);
                cartItemView.Author = _authorService.GetAuthorById(cartItemView.Book.AuthorId);
                cartItemView.CartItem = cartItem;

                return cartItemView;
            });
        }
    }
}

Knigochei/Controllers/OrderController.cs
using Knigochei.Models;
using Knigochei.Services.BookService;
using Knigochei.Services.CartService;
using Knigochei.Services.OrderService;
using Knigochei.Services.UserService;
using Knigochei.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Knigochei.Controllers
{
	[Authorize(Roles = "Admin,Customer")]
	public class OrderController : Controller
	{
		private ICartService _cartService;
		private IBookService _bookService;
		private IOrderService _orderService;
		private IUserService _userService;

		public OrderController(ICartService cartService, IOrderService orderService, IUserService userService, IBookService bookService)
		{
			_cartService = cartService;
			_orderService = orderService;
			_userService = userService;
			_bookService = bookService;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult CreateOrder()
		{
			int userId = GetUserId();
			List<CartItem> cartItems = _cartService.GetAllCartItemsByCart(userId);
			User user = _userService.GetUserById(userId);
			IEnumerable<OrderItemViewModel> orderItemViewModels = ConvertCartItemsToOrderItemsViewModel(cartItems); 

			OrderViewModel orderViewModel = new OrderViewModel();
			orderViewModel.User = user;
			orderViewModel.OrderItems = orderItemViewModels;
			orderViewModel.TotalPrice = orderItemViewModels.Sum(item => item.TotalAmountPrice);


			return View(orderViewModel);
		}

		[HttpPost]
		public IActionResult CreateOrder(string pickUpAddress, int totalPrice)
		{
			int userId = GetUserId();
			List<CartItem> cartItems = _cartService.GetAllCartItemsByCart(userId);

			Order order = new Order();
			order.OrderDate = DateTime.Now;
			order.DeliveryDate = DateTime.Now.AddDays(7);
			order.UserId = userId;
			order.PickUpAddress = pickUpAddress;
			order.OrderStatusId = (int)OrderStatus.Created;
			order.TotalPrice = totalPrice;

			_orderService.CreateNewOrder(order);

			_orderService.CreateOrderItemsFromCartItems(order, cartItems);

			_cartService.ClearUserCart(userId);

			return new JsonResult("Success");
		}

		
		public IActionResult OrderHistory()
		{
			int userId = GetUserId();
			List<Order> orders = _orderService.GetOrdersByUser(userId);
			User user = _userService.GetUserById(userId);

			OrderHistoryViewModel orderHistory = new OrderHistoryViewModel();
			orderHistory.Orders = orders;
			orderHistory.User = user;

			return View(orderHistory);
		}
		public int GetUserId()
		{
			string userIdClaimValue = HttpContext.User.Claims
				.Where(claim => claim.Type == ClaimTypes.NameIdentifier)
				.Select(claim => claim.Value)
				.FirstOrDefault();


			return Convert.ToInt32(userIdClaimValue);
		}

		public IEnumerable<OrderItemViewModel> ConvertCartItemsToOrderItemsViewModel(IEnumerable<CartItem> cartItems)
		{
			return cartItems.Select(cartItem =>
			{
				OrderItemViewModel orderItemViewModel = new OrderItemViewModel();
				orderItemViewModel.Book = _bookService.GetBookById(cartItem.BookId);
				orderItemViewModel.CartItem = cartItem;
				orderItemViewModel.TotalAmountPrice = orderItemViewModel.Book.Price * cartItem.Amount;


				return orderItemViewModel;
			});
		}
	}
}

Knigochei/Views/Cart/Index.cshtml
@model List<Knigochei.ViewModels.CartItemViewModel>
@using System.Globalization

@{
	DateOnly now = DateOnly.FromDateTime(DateTime.Now);
	
	ViewData["Title"] = "Корзина";
}


<div class="container-fluid">
	<div class="row pb-0 mb-0 pt-5 mt-4">
		<div class="col-md-8 ms-0">
			<div class="row p-2 ms-4">
				<table class="text-center" id="items">
					<tr>
						<th class="col-md-2">&nbsp;</th>
						<th class="col-md-2">Цена:</th>
						<th class="col-md-2">Кол-во:</th>
						<th class="col-md-2">Стоимость:</th>
						<th class="col-md-2">&nbsp;</th>
					</tr>
					@foreach(var cartItem in Model)
					{
						<tr>
							<td>
								<h5> @cartItem.Book.Title </h5>
								<h6> @cartItem.Author.FullName</h6>
								<span>
									@for(int star = 0; star < @cartItem.Book.BookRank; star++)
									{
										<i class="bi bi-star-fill"></i>
									}
								</span> 
							</td>
							<td>
								<h6 id="price-@cartItem.CartItem.BookId"> @cartItem.Book.Price<span> KZT </span> </h6>
							</td>
							<td>  
								
								<input type="number" class="text-center w-25 amount" id="@cartItem.CartItem.BookId"  name="amount" value=@cartItem.CartItem.Amount min=1 style="border: 1px solid black">
								
							</td>
							<td>
								<h6 id="total-amount-@cartItem.CartItem.BookId">@(cartItem.CartItem.Amount * cartItem.Book.Price)<span> KZT </span> </h6>
							</td>
							<td> <button class="del" onclick="deleteCartItem(@cartItem.CartItem.BookId)"> Удалить </button> </td>
						</tr>
					}

				</table>
			</div>
		</div>
		<div class="col-md-3 ms-5 pt-4 cartItem text-center">
			<h4 id="total-price"></h4> <hr>
			<p> Сформируем заказ: <span>@now.ToString("dd MMMM", CultureInfo.CreateSpecificCulture("ru"))</span> </p>
			<p> Отправим заказ:<span> @now.AddDays(7).ToString("dd MMMM", CultureInfo.CreateSpecificCulture("ru")) </span> </p>
			<button class="mt-5 p-2" onclick="creteOrderPage()"> Оформить заказ </button>
		</div>
	</div>
<br> <br> <br> <br> <br> <br> <br> <br> <br>

<script>
	function deleteCartItem(bookId) {
			console.log('@Url.Action("DeleteFromCart", "Cart")')
			$.ajax({
				url: '@Url.Action("DeleteFromCart", "Cart")',
				method: "DELETE",
				data: {
					"bookId":bookId,
				},
				success: function(data, statusCode) {
					console.log(data)
					refreshPage();
				},
				error: function(errorCode) {
					alert("Could not delete Item From Cart!")
					
				}
			})
		};
	function creteOrderPage() {
		location.href = '@Url.Action("CreateOrder", "Order")';
	}
	function refreshPage() {
		document.location.reload();
	}
	$("document").ready(function() {
		refreshTotalPrice();
		$(".amount").change(function() {
			let amount = Number($(this).val());
			if(amount <= 0) {
				amount = 1;
				$(this).val(1)
			}
			console.log("Item Change")
			let bookId = $(this).attr('id');
			let price = Number($("#price-"+bookId).text().match("[0-9]+"))
			
			updateCartItemAmount(bookId, price, amount);
			
		})
		function refreshTotalPrice() {
			let total = 0;
			$(".amount").each(function(index) {
				let bookId = $(this).attr('id');
				let amount = Number($(this).val());
				let price = Number($("#price-"+bookId).text().match("[0-9]+"))
				total+=amount*price;
			})
			$("#total-price").text("Итоговая сумма : ").append(total).append(" KZT");
		}
		function updateCartItemAmount(bookId, price, amount) {
			$.ajax({
				url: '@Url.Action("UpdateCartItemAmount", "Cart")',
				method: "POST",
				data: {
					"BookId":bookId,
					"Amount":amount
				},
				success: function(data, statusCode) {
					console.log("Cart Item Amount Updated!")
					$("#total-amount-"+bookId).text(price*amount).append(" KZT");
					refreshTotalPrice();
				},
				error: function(errorCode) {
					console.log("Error Updating Amount!")
					
				}
			})
		}
	})
</script>